### ISSUE TITLE
Rename testnode in sara_shield

### ISSUE THREAD

**Issue by JakobThumm** [manuelvogel12/sara-shield#2]
Testnode should be purged from existence.

**Comment by JakobThumm** [comment]
On which merge request was this resolved?

**Comment by manuelvogel12** [comment]
Resolved with commit https://github.com/manuelvogel12/sara-shield/commit/908335955ff0df0a714b3d4afe8d8539f6ca8bd7

**Comment by JakobThumm** [comment]
Okay! For bigger changes, please create pull requests in the future and always tag the resolving commit or PR :)
