### ISSUE TITLE
Adapt the CONCERT capsules

### ISSUE THREAD

**Issue by JakobThumm** [manuelvogel12/sara-shield#4]
Adapt the concert capsules so that all robot parts are encapsulated.
Also add the drill as an optional end-effector.

**Comment by manuelvogel12** [comment]
By changing
`<arg name="modular_description" default="$(find concert_examples)/concert_example.py"/>` to `<arg name="modular_description" default="$(find concert_examples)/concert_example_with_drill.py"/>`
in `concert_description/concert_gazebo/launch/concert.launch`, the drill can be added. Rerunning the capsule generation script is enough for a capsule that is big enough:
![image](https://github.com/manuelvogel12/sara-shield/assets/120781514/293e565e-908a-4bac-b59f-648648f9e2d3)

**Comment by manuelvogel12** [comment]
With the new version of the script, the capsules also encapsulate the robot in the starting position perfectly. Only after moving, problems occur. Since that problem is already mentioned in #5, I will close this issue
