### ISSUE TITLE
Publish safety status of sara-shield on a ROS topic

### ISSUE THREAD

**Issue by JakobThumm** [manuelvogel12/sara-shield#6]
By publishing if the shield is safe on a ROS topic, we can empower more robot functionalities with safety, e.g., turn off the drill.
Topic name: `/sara_shield/is_safe`, Bool

**Comment by JakobThumm** [comment]
On which merge request was this resolved?

**Comment by manuelvogel12** [comment]
It was resolved with commit `5035a2b`
