### ISSUE TITLE
Enable multiple human safety

### ISSUE THREAD

**Issue by JakobThumm** [manuelvogel12/sara-shield#8]
Allow safety for multiple humans in the scene.
If runtime becomes a concern, we can reduce the number of models (pos, vel, acc) that is checked to vel only.

**Comment by manuelvogel12** [comment]
How is this supposed to work? Should multiple sara-shields be running? Or should I implement the functionality in sara-shield?

**Comment by JakobThumm** [comment]
Implement the functionality in sara-shield. It would be best if you had multiple human_reach models, I think.

**Comment by manuelvogel12** [comment]
Core functionality was added in https://github.com/manuelvogel12/sara-shield/pull/9, still some work to be done

**Comment by manuelvogel12** [comment]
Commit https://github.com/manuelvogel12/human-gazebo/commit/049a6552d7931d746746a0f5fa39cd4a84e66ce3 added the multiple humans functionality to the simulation. The code has now been successfully tested with multiple simulated humans. 
Only things left to do:

- [x] decide on how to determine the max number of humans (mentioned in #9 )
- [x] make sure Profactor outputs a consistent label_id for the same human, and uses a new one whenever a new human enters the scene
- [x] Merge Pull Request #9
